/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TitleAbstract } from '../../models/title-abstract';

export interface TitleAbstractGet$Params {
}

export function titleAbstractGet(http: HttpClient, rootUrl: string, params?: TitleAbstractGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TitleAbstract>>> {
  const rb = new RequestBuilder(rootUrl, titleAbstractGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TitleAbstract>>;
    })
  );
}

titleAbstractGet.PATH = '/TitleAbstract';
