/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TitleAbstract } from '../../models/title-abstract';

export interface TitleAbstractIdGet$Plain$Params {
  id: number;
}

export function titleAbstractIdGet$Plain(http: HttpClient, rootUrl: string, params: TitleAbstractIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TitleAbstract>> {
  const rb = new RequestBuilder(rootUrl, titleAbstractIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TitleAbstract>;
    })
  );
}

titleAbstractIdGet$Plain.PATH = '/TitleAbstract/{id}';
