/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TitleAbstract } from '../../models/title-abstract';

export interface TitleAbstractOrderIdGet$Params {
  orderId: string;
}

export function titleAbstractOrderIdGet(http: HttpClient, rootUrl: string, params: TitleAbstractOrderIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TitleAbstract>> {
  const rb = new RequestBuilder(rootUrl, titleAbstractOrderIdGet.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TitleAbstract>;
    })
  );
}

titleAbstractOrderIdGet.PATH = '/TitleAbstract/{orderId}';
