/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TitleAbstract } from '../../models/title-abstract';

export interface TitleAbstractPost$Plain$Params {
      body?: TitleAbstract
}

export function titleAbstractPost$Plain(http: HttpClient, rootUrl: string, params?: TitleAbstractPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TitleAbstract>> {
  const rb = new RequestBuilder(rootUrl, titleAbstractPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TitleAbstract>;
    })
  );
}

titleAbstractPost$Plain.PATH = '/TitleAbstract';
