/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { Assignments } from './models/assignments';
export { Client } from './models/client';
export { Deed } from './models/deed';
export { Judgment } from './models/judgment';
export { LegalDescription } from './models/legal-description';
export { Mortgage } from './models/mortgage';
export { ProductType } from './models/product-type';
export { Property } from './models/property';
export { TaxSheet } from './models/tax-sheet';
export { TaxSheetUtility } from './models/tax-sheet-utility';
export { TitleAbstract } from './models/title-abstract';
