/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Assignments {
  amount?: number | null;
  assignee?: string | null;
  assignmentLanguage?: string | null;
  assignmentType?: string | null;
  book?: string | null;
  bookPageInstrumentLanguage?: string | null;
  dated?: string | null;
  datingLanguage?: string | null;
  document?: string | null;
  filed?: string | null;
  id?: number | null;
  mortgage_Type_ID?: number | null;
  page?: string | null;
}
