/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Deed {
  book?: string | null;
  consideration?: number | null;
  date?: string | null;
  document_Series?: string | null;
  grantee_Name?: string | null;
  grantor_Name?: string | null;
  id?: number;
  misc?: string | null;
  other_Ownership_Type?: string | null;
  ownership_Type?: string | null;
  page?: string | null;
  recorded?: string | null;
}
