/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Judgment {
  addsReleaseScheduleB1?: boolean;
  amount?: number | null;
  book?: string | null;
  caseNumber?: string | null;
  defendantName?: string | null;
  defendantType?: string | null;
  documentInstrumentNumber?: string | null;
  filedDate?: string | null;
  id?: number;
  misc?: string | null;
  name?: string | null;
  page?: string | null;
  plaintiffName?: string | null;
  plaintiffType?: string | null;
  releasedDate?: string | null;
}
