/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Assignments } from '../models/assignments';
export interface Mortgage {
  assignments?: Array<Assignments> | null;
  book?: string | null;
  case_Filed_Date?: string | null;
  contact_Info?: string | null;
  county?: string | null;
  doc_Number?: string | null;
  document?: string | null;
  executed?: string | null;
  filed?: string | null;
  foreclosing_Case_Number?: string | null;
  foreclosing_Party?: string | null;
  i_Mortgage_Type?: string | null;
  id?: number;
  instrument?: string | null;
  item?: string | null;
  jurisdiction?: string | null;
  last_Action?: string | null;
  misc?: string | null;
  mortgage_Amount?: number | null;
  mortgagee?: string | null;
  new_Owner?: string | null;
  page?: string | null;
  plaintiff_Attorney?: string | null;
  release_Requirement?: string | null;
  sale_Date?: string | null;
  signed_By?: string | null;
  state?: string | null;
  trustee?: string | null;
}
