/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Property {
  address?: string | null;
  city?: string | null;
  county?: string | null;
  propertyID?: number;
  propertyType?: string | null;
  state?: string | null;
  zipCode?: string | null;
}
