/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxSheetUtility } from '../models/tax-sheet-utility';
export interface TaxSheet {
  baseAmount?: number | null;
  delinquentAmount?: number | null;
  frequency?: string | null;
  id?: number;
  payee?: string | null;
  payeeAddress1?: string | null;
  payeeAddress2?: string | null;
  payeeCity?: string | null;
  payeePhone?: string | null;
  payeeState?: string | null;
  payeeZip?: string | null;
  paymentType?: string | null;
  status?: string | null;
  taxID?: string | null;
  taxSheetUtilities?: Array<TaxSheetUtility> | null;
  taxYear?: string | null;
}
