/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaxSheetUtility {
  id?: number;
  payee?: string | null;
  payeeAddress1?: string | null;
  payeeAddress2?: string | null;
  payeeCity?: string | null;
  payeePhone?: string | null;
  payeeState?: string | null;
  payeeZip?: string | null;
  utilityAmount?: number | null;
  utilityFrequency?: string | null;
  utilityType?: string | null;
}
