/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Client } from '../models/client';
import { Deed } from '../models/deed';
import { Judgment } from '../models/judgment';
import { LegalDescription } from '../models/legal-description';
import { Mortgage } from '../models/mortgage';
import { ProductType } from '../models/product-type';
import { Property } from '../models/property';
import { TaxSheet } from '../models/tax-sheet';
export interface TitleAbstract {
  client?: Client;
  clientRefNo?: string | null;
  deeds?: Array<Deed> | null;
  effectiveDate?: string;
  judgments?: Array<Judgment> | null;
  legalDescriptions?: Array<LegalDescription> | null;
  mortgages?: Array<Mortgage> | null;
  orderNo?: string | null;
  productType?: ProductType;
  property?: Property;
  searchDate?: string;
  taxSheets?: Array<TaxSheet> | null;
  titleAbstractID?: number;
}
